// scripts/buildZamcelcoOutages.ts — run in Node after editing src/zamcelcoOutages.csv.
//
//   npx tsx scripts/buildZamcelcoOutages.ts
//
// Checks the cleaned ZAMCELCO interruption list (Barangays, Datetime Start, Datetime End,
// ZAMCELCO Description) and writes src/zamcelcoOutages.ts, which the quote page offers as
// the built-in outage history. Stops if any row can't be read.

import * as fs from 'fs';
import * as path from 'path';
import { parseOutageCsv } from '../src/solarQuoteCalculator';

const src = path.join(__dirname, '..', 'src', 'zamcelcoOutages.csv');
const csv = fs.readFileSync(src, 'utf8');
const result = parseOutageCsv(csv);

if (result.skipped.length > 0) {
  result.skipped.forEach((s) => console.error(`line ${s.line}: ${s.reason}  [${s.raw}]`));
  console.error('Fix these rows. Nothing was written.');
  process.exit(1);
}
const lines = csv.trim().split('\n').slice(1);
const rows = lines.length;
const noBarangay = lines.filter((l) => l.startsWith(',')).length;
console.log(`Rows: ${rows} (${noBarangay} with no barangay), ${result.firstStart} to ${result.lastEnd}`);
console.log(`Barangays: ${Object.keys(result.locations).length}`);

const out = path.join(__dirname, '..', 'src', 'zamcelcoOutages.ts');
fs.writeFileSync(
  out,
  '// Generated by scripts/buildZamcelcoOutages.ts from zamcelcoOutages.csv. Edit the CSV, not this file.\n\n' +
    `export const ZAMCELCO_OUTAGES_CSV = ${JSON.stringify(csv)};\n`,
);
console.log(`Wrote ${out}`);
