// scripts/buildSunProfile.ts — run once in Node, not part of the app bundle.
//
//   npx tsx scripts/buildSunProfile.ts <files or folders...> [--device "Name"] [--date-order DMY|MDY]
//
// Examples:
//   npx tsx scripts/buildSunProfile.ts ~/Downloads/solar-export
//   npx tsx scripts/buildSunProfile.ts week1.xlsx week2.xlsx week3.xlsx
//
// Reads every inverter export (Device Name, Time, PV1 Input Power (kW)), combines them
// (overlapping readings are counted once), and writes src/zamboangaSunProfile.ts,
// which the calculator uses as its default.

import * as fs from 'fs';
import * as path from 'path';
import * as XLSX from 'xlsx';
import { buildSunProfile, DateOrder, SunOutputRow } from '../src/solarQuoteCalculator';

const OPTIONS_WITH_VALUE = ['--device', '--date-order'];

function arg(name: string): string | undefined {
  const i = process.argv.indexOf(name);
  return i > 0 ? process.argv[i + 1] : undefined;
}

// Positional arguments: files or folders
const inputs = process.argv.slice(2).filter((a, i, all) =>
  !a.startsWith('--') && !OPTIONS_WITH_VALUE.includes(all[i - 1]));
if (inputs.length === 0) {
  console.error('Usage: npx tsx scripts/buildSunProfile.ts <files or folders...> [--device NAME] [--date-order DMY|MDY]');
  process.exit(1);
}

const files = inputs.flatMap((p) => {
  if (!fs.existsSync(p)) {
    console.error(`Not found: ${p}`);
    process.exit(1);
  }
  if (fs.statSync(p).isDirectory()) {
    return fs.readdirSync(p)
      .filter((f) => /\.xlsx$/i.test(f) && !f.startsWith('~$')) // skip Excel lock files
      .sort()
      .map((f) => path.join(p, f));
  }
  return [p];
});
if (files.length === 0) {
  console.error('No .xlsx files found.');
  process.exit(1);
}

/** Reads one export into row objects. Finds the header row even if a title sits above it. */
function readExport(file: string): SunOutputRow[] {
  // cellDates: false keeps Excel dates as serial numbers. The calculator converts those
  // without any timezone, so the result does not depend on this computer's settings.
  const workbook = XLSX.readFile(file, { cellDates: false });
  const sheet = workbook.Sheets[workbook.SheetNames[0]];
  const grid = XLSX.utils.sheet_to_json<unknown[]>(sheet, { header: 1, raw: true, defval: null });
  const headerRow = grid.findIndex(
    (r) => r.some((c) => String(c ?? '').trim() === 'Time') &&
      r.some((c) => /PV1 Input Power/i.test(String(c ?? ''))),
  );
  if (headerRow < 0) {
    throw new Error(`${path.basename(file)}: no header row with "Time" and "PV1 Input Power (kW)".`);
  }
  const headers = grid[headerRow].map((c) => String(c ?? '').trim());
  return grid.slice(headerRow + 1).map((r) => {
    const obj: Record<string, unknown> = {};
    headers.forEach((h, i) => { if (h) obj[h] = r[i]; });
    return obj as SunOutputRow;
  });
}

const rows: SunOutputRow[] = [];
console.log(`Reading ${files.length} file(s):`);
for (const f of files) {
  const r = readExport(f);
  console.log(`  ${path.basename(f)}: ${r.length} rows`);
  rows.push(...r);
}

const result = buildSunProfile(rows, {
  deviceName: arg('--device'),
  dateOrder: arg('--date-order') as DateOrder | undefined,
  sourceSystemKwp: 1.95, // 3 × 650 W
});

const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
console.log(`\nCovers ${result.firstDay} to ${result.lastDay}, logging every ${result.sampleIntervalMinutes} min`);
console.log(`Rows skipped: ${result.rowsSkipped}, duplicate readings merged: ${result.duplicatesMerged}, days excluded: ${result.daysExcluded}`);
months.forEach((m, i) => {
  const days = result.daysUsedByMonth[i];
  const label = days > 0 ? `from ${days} days` : '(no data: all-month average used)';
  console.log(`  ${m}: ${result.dailyYieldByMonth[i].toFixed(2)} kWh/kWp/day ${label}`);
});
result.warnings.forEach((w) => console.warn(`WARNING: ${w}`));

const out = path.join(__dirname, '..', 'src', 'zamboangaSunProfile.ts');
const rounded = result.profile.monthly.map((row) => row.map((v) => Math.round(v * 1e5) / 1e5));
fs.writeFileSync(
  out,
  `// zamboangaSunProfile.ts — generated by scripts/buildSunProfile.ts\n` +
  `// from ${files.length} export(s), ${result.firstDay} to ${result.lastDay}.\n` +
  `// kWh per kWp for each [month][hour]. Do not edit by hand.\n\n` +
  `import type { SunProfile } from './solarQuoteCalculator';\n\n` +
  `export const ZAMBOANGA_SUN_PROFILE: SunProfile = ${JSON.stringify(
    { monthly: rounded, source: result.profile.source }, null, 2,
  )};\n`,
);
console.log(`\nWrote ${out}`);
